### ISSUE TITLE
:( I tried so many times but keep saying :

### ISSUE THREAD

**Issue by FanOfZhouwei** [MrCrayfish/MrCrayfishFurnitureMod-MCPE#28]
java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1306]:   155 cannot locate '_ZN4Item15addCreativeItemEPS_s'...

	at java.lang.Runtime.load(Runtime.java:340)
	at java.lang.System.load(System.java:521)
	at com.mojang.minecraftpe.MainActivity.loadNativeAddons(MainActivity.java:1569)
	at com.mojang.minecraftpe.MainActivity.onCreate(MainActivity.java:338)
	at net.zhuoweizhang.mcpelauncher.pro.LauncherProActivity.onCreate(LauncherProActivity.java:35)
	at android.app.Activity.performCreate(Activity.java:5008)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2031)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2092)
	at android.app.ActivityThread.access$600(ActivityThread.java:133)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4797)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by minecraftmuse3** [comment]
@FanOfZhouwei You're not on 0.11.0

**Comment by FanOfZhouwei** [comment]
Ohhh sorry now I know

**Comment by Koolman12** [comment]
Is this pe like pc?

**Comment by FanOfZhouwei** [comment]
And can you post the download link of this mod ;) thanks

**Comment by Koolman12** [comment]
Is this pe like pc????

**Comment by FanOfZhouwei** [comment]
@minecraftmuse3 or @MrCrayfish can you gave me the link of this model Thanks lavya ;)

**Comment by FanOfZhouwei** [comment]
*MOd

**Comment by CrazyWolf23** [comment]
@Koolman12 No, this is furniturePE, PE like PC is a private addon made by Smart DEV. You`ll see updates of that addon on twitter, follow @CrazyWolf23_YT_ on Twitter.

**Comment by FanOfZhouwei** [comment]
@CrazyWolf23 can u gave me the download link ofthis mod

**Comment by FanOfZhouwei** [comment]
The updated one pls

**Comment by Koolman12** [comment]
Here

**Comment by Koolman12** [comment]
https://www.dropbox.com/s/nqpqfeag6cj2tcu/MrCrayfishFurnitureMod-MCPE-master.apk?dl=1

**Comment by FanOfZhouwei** [comment]
And I download the link on drop box also keep saying detect a crash and it will disable patches or modifications why I'm using mcpe 0.11 and blocklauncher 0.9

**Comment by FanOfZhouwei** [comment]
Or post the link in Here of 0.11 and blocklauncher

**Comment by FanOfZhouwei** [comment]
Plss reply

**Comment by CrazyWolf23** [comment]
Just update it in the google play store, (Unless your on windows, idk nothing about windows phones)

**Comment by FanOfZhouwei** [comment]
Yes yes yes thanks , all of u thanks now I get it can I request to @byteandelhalf ??? Can you make your pocket power compatible in 0.11.1 ^_^ thanks

**Comment by RedstoneGunMade** [comment]
@CrazyWolf23 I can't talk in twitter!

**Comment by CrazyWolf23** [comment]
@RedstoneGunMade why?

**Comment by FanOfZhouwei** [comment]
Any updates ??

**Comment by Koolman12** [comment]
No

**Comment by Koolman12** [comment]
Ill send u the latest update

**Comment by Koolman12** [comment]
https://www.dropbox.com/s/nqpqfeag6cj2tcu/MrCrayfishFurnitureMod-MCPE-master.apk?dl=1

**Comment by FanOfZhouwei** [comment]
Okay thanks

**Comment by Koolman12** [comment]
:) dude

**Comment by FanOfZhouwei** [comment]
Ahmmmm @MrCrayfish can you add some soartex texture pack that support this mod possess =) or other texture pack

**Comment by skullkeeper94** [comment]
@FanOfZhouwei any texture pack should support this (except for mods).

**Comment by RedstoneGunMade** [comment]
is supported all textures (less items)
